export const READ_APPLICATION_ERRORS = 'READ_APPLICATION_ERRORS';
export const READ_APPLICATION_TITLES = 'READ_APPLICATION_TITLES';
export const READ_STAFF_REVIEWERS = 'READ_STAFF_REVIEWERS';


export const SEND_APPLICATION_ALERTS_FORGOT = 'SET_APPLICATION_ALERTS_FORGOT';
export const SEND_APPLICATION_ALERTS_REGISTERED = 'SET_APPLICATION_ALERTS_REGISTERED';
export const SEND_APPLICATION_ALERTS_UPDATED = 'SET_APPLICATION_ALERTS_UPDATED';

export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_THEME = 'SET_THEME';
export const SET_MODE = 'SET_MODE';

export const SET_SORTS_AUTHORUP = 'SET_SORTS_AUTHORUP';
export const SET_SORTS_AUTHORDOWN = 'SET_SORTS_AUTHORDOWN';
export const SET_SORTS_REVIEWERUP = 'SET_SORTS_REVIEWERUP';
export const SET_SORTS_REVIEWERDOWN = 'SET_SORTS_REVIEWERDOWN';
export const SET_SORTS_TITLEUP = 'SET_SORTS_TITLEUP';
export const SET_SORTS_TITLEDOWN = 'SET_SORTS_TITLEDOWN';
export const SET_SORTS_RECENTNEWEST = 'SET_SORTS_RECENTNEWEST';
export const SET_SORTS_RECENTOLDEST = 'SET_SORTS_RECENTOLDEST';
export const SET_SORTS_STATUSUP = 'SET_SORTS_STATUSUP';
export const SET_SORTS_STATUSDOWN = 'SET_SORTS_STATUSDOWN';

export const SET_FILTERS_TEXT = 'SET_FILTERS_TEXT';

export const SET_CENTERED_MAP = 'SET_CENTERED_MAP';

export const SET_ACCOUNT_LOADING = 'SET_ACCOUNT_LOADING';
export const SET_ACCOUNT_AUTH = 'SET_ACCOUNT_AUTH';
export const SET_ACCOUNT_AVATAR = 'SET_ACCOUNT_AVATAR';
export const SET_ACCOUNT_USER = 'SET_ACCOUNT_USER';
export const SET_ACCOUNT_PROFILE = 'SET_ACCOUNT_PROFILE';
export const CLEAR_APPLICATION_ALERTS = 'CLEAR_APPLICATION_ALERTS';
export const CLEAR_APPLICATION_ERRORS = 'CLEAR_APPLICATION_ERRORS';

export const VERIFY_APPLICATION_ALERTS = 'VERIFY_APPLICATION_ALERTS';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';

export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const POST_LOADING = 'POST_LOADING';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_CONTRIBUTION = 'GET_CONTRIBUTION';
export const GET_CONTRIBUTIONS = 'GET_CONTRIBUTIONS';
export const CONTRIBUTIONS_LOADING = 'CONTRIBUTIONS_LOADING';

export const GET_VIENTO = 'GET_VIENTO';
export const GET_VIENTOS = 'GET_VIENTOS';
export const VIENTOS_MAP = 'VIENTOS_MAP';
export const VIENTOS_LOADING = 'VIENTOS_LOADING';
export const VIENTOS_VISIBLE = 'VIENTOS_VISIBLE';
